[project]
name = "codestral-pytorch-rocm-env"
version = "0.1.0"
description = "A Pixi environment for PyTorch (ROCm) and Hugging Face Transformers to use Mistral Codestral on AMD GPUs."
authors = ["Vanessa Sochat <sochat1@llnl.gov>"]
license = "MIT"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"] 

[dependencies]
python = ">=3.10,<3.12"
pip = ">=25.1.1,<26"
ipython = ">=9.2.0,<10"
boto3 = ">=1.38.19,<2"
transformers = ">=4.52.0,<5"
mistral-common = ">=1.5.4,<2"
protobuf = ">=5.29.3,<6"

[tasks]
# Task to install PyTorch, torchvision, torchaudio for ROCm 6.2 using your specific pip command.
# This should be run AFTER `pixi install` has set up the base Python environment and other dependencies.
install-pytorch-rocm62 = "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2"

# --- Hugging Face & Mistral Libraries ---
transformers = ">=4.40"
accelerate = ">=0.29"
sentencepiece = "*"     
protobuf = "*"          
tiktoken = "*"          
mistral-common = ">=0.1.3"
